
- name: ensure quagga is running
  service: name=quagga state=started

- name: configure quagga daemons file
  copy: src=daemons dest=/etc/quagga/daemons
  notify:
    - check quagga
    - restart quagga

- name: configure quagga configuration
  template: src=Quagga.conf.j2 dest=/etc/quagga/Quagga.conf
  notify:
    - check quagga
    - restart quagga
