---
- hosts: leafs
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - leafs
- hosts: spines
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - spines
- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - servers
