---
- hosts: switches
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ospf-numbered-ipv6
- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - servers
