---
- hosts: switches
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - bgp-unnumbered
  handlers:
    - include : handlers/main.yml
- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - servers
  handlers:
    - include : handlers/main.yml
